---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment-v1
  namespace: api
  labels:
    app: demo-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: v1
  template:
    metadata:
      labels:
        app: demo-app
        version: v1
    spec:
      containers:
      - name: demo-app
        image: com.example/demo-app:1.1
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
        readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
        resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment-v2
  namespace: api
  labels:
    app: demo-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: v2
  template:
    metadata:
      labels:
        app: demo-app
        version: v2
    spec:
      containers:
      - name: demo-app
        image: com.example/demo-app:1.2
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
        readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
        resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment-v2.1
  namespace: api
  labels:
    app: demo-app
    version: v2.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: v2.1
  template:
    metadata:
      labels:
        app: demo-app
        version: v2.1
        minorVersion: v1
    spec:
      containers:
      - name: demo-app
        image: com.example/demo-app:1.2.1
        ports:
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
        readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
        resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
