---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: demo-app-service
  labels:
    app: demo-app
    service: demo-app-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http-web
  type: ClusterIP
  selector:
    app: demo-app
